openapi: 3.0.3
info:
  title: Party Registry Proxy Server
  description: This service is the proxy to the party registry
  version: 0.0.1
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com
  termsOfService: http://localhost/terms
  x-api-id: an x-api-id
  x-summary: an x-summary
servers:
  - url: https://localhost/pdnd-interop-uservice-party-registry-proxy/v0.0.1
    description: This service is the proxy to the party registry
tags:
  - name: institution
    description: Retrieve information about institution
    externalDocs:
      description: Find out more
      url: http://swagger.io
  - name: health
    description: Verify service status
    externalDocs:
      description: Find out more
      url: http://swagger.io

paths:
  /institutions:
    get:
      tags:
        - institution
      summary: Retriev all the institutions paginated
      description: Returns institutions paginated
      operationId: getInstitutions
      parameters:
        - name: limit
          in: query
          description: limit for pagination
          required: true
          schema:
            type: integer
            format: int32
        - name: offset
          in: query
          description: for pagination
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Paginated'
        '400':
          description: Invalid ID supplied
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Institution not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /institutions/{institutionId}:
    get:
      tags:
        - institution
      summary: Find institution by ID
      description: Returns a single institution
      operationId: getInstitutionById
      parameters:
        - name: institutionId
          in: path
          description: ID of institution to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Institution'
        '400':
          description: Invalid ID supplied
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Institution not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /status:
    get:
      tags:
        - health
      summary: Health status endpoint
      description: Return ok
      operationId: getStatus
      responses:
        '200':
          description: successful operation
          content:
            application/problem+json:
              schema:
                $ref: 'https://teamdigitale.github.io/openapi/0.0.7/definitions.yaml#/schemas/Problem'
components:
  schemas:
    Institution:
      type: object
      properties:
        id:
          type: string
          example: age
        dn:
          type: string
          example: aoo=agd_DG,o=agd,c=it
        description:
          type: string
          example: AGENCY X
        pec:
          type: string
          example: mail@pec.mail.org
      required:
        - id
        - dn
        - description
        - pec
    Paginated:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Institution'
        totalCount:
          type: integer
          format: int32
      required:
        - items
        - totalCount
    ErrorResponse:
      type: object
      properties:
        detail:
          type: string
        type:
          type: string
        title:
          type: string
        status:
          type: string
      required:
        - detail
        - type
        - title
        - status