openapi: 3.0.3
info:
  title: Party Registry Proxy Server
  description: This service is the proxy to the party registry
  version: 0.0.1
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com
  termsOfService: http://localhost/terms
  x-api-id: an x-api-id
  x-summary: an x-summary
servers:
  - url: https://localhost/pdnd-interop-uservice-party-registry-proxy/v0.0.1
    description: This service is the proxy to the party registry
tags:
  - name: institution
    description: Retrieve information about institution
    externalDocs:
      description: Find out more
      url: http://swagger.io
  - name: health
    description: Verify service status
    externalDocs:
      description: Find out more
      url: http://swagger.io

paths:
  /institutions:
    get:
      tags:
        - institution
      summary: Retriev all the institutions paginated
      description: Returns institutions paginated
      operationId: getInstitutions
      parameters:
        - name: limit
          in: query
          description: limit for pagination
          required: true
          schema:
            type: integer
            format: int32
            maximum: 100
            minimum: 10
        - name: offset
          in: query
          description: for pagination
          required: true
          schema:
            type: integer
            format: int32
            maximum: 1000
            minimum: 10
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Paginated'
        '400':
          description: Invalid ID supplied
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Institution not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /institutions/{institutionId}:
    get:
      tags:
        - institution
      summary: Find institution by ID
      description: Returns a single institution
      operationId: getInstitutionById
      parameters:
        - name: institutionId
          in: path
          description: ID of institution to return
          required: true
          schema:
            type: string
            maxLength: 32
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Institution'
        '400':
          description: Invalid ID supplied
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Institution not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /status:
    get:
      tags:
        - health
      summary: Health status endpoint
      description: Return ok
      operationId: getStatus
      responses:
        '200':
          description: successful operation
          content:
            application/problem+json:
              schema:
                $ref: 'https://teamdigitale.github.io/openapi/0.0.7/definitions.yaml#/schemas/Problem'
components:
  schemas:
    Institution:
      type: object
      additionalProperties: false
      properties:
        id:
          type: string
          example: age
          format: 'ˆ[a-z]{1,3}$'
          maxLength: 3
        dn:
          type: string
          example: aoo=agd_DG,o=agd,c=it
          maxLength: 32
        taxCode:
          type: string
          example: '00000000000'
          pattern: '[\d]{10,13}'
          maxLength: 13
        managerTaxCode:
          type: string
          example: RSSMRA75L01H501A
          pattern: '^(?:(?:[B-DF-HJ-NP-TV-Z]|[AEIOU])[AEIOU][AEIOUX]|[B-DF-HJ-NP-TV-Z]{2}[A-Z]){2}[\dLMNP-V]{2}(?:[A-EHLMPR-T](?:[04LQ][1-9MNP-V]|[1256LMRS][\dLMNP-V])|[DHPS][37PT][0L]|[ACELMRT][37PT][01LM])(?:[A-MZ][1-9MNP-V][\dLMNP-V]{2}|[A-M][0L](?:[1-9MNP-V][\dLMNP-V]|[0L][1-9MNP-V]))[A-Z]$'
          maxLength: 16
        managerName:
          type: string
          example: Mario
          format: 'ˆ[A-Za-z èàòùìÈÀÒÙÌ]{2,30}$'
          maxLength: 30
        managerSurname:
          type: string
          example: Rossi
          format: 'ˆ[A-Za-z èàòùìÈÀÒÙÌ]{2,30}$'
          maxLength: 30
        description:
          type: string
          example: AGENCY X
          format: 'ˆ[A-Za-z èàòùìÈÀÒÙÌ]{2,30}$'
          maxLength: 30
        digitalHome:
          type: string
          example: mail@pec.mail.org
          format: mail
          maxLength: 20
        activationDate:
          type: string
          example: 2013-01-10
          format: date
        deactivationDate:
          type: string
          example: 2013-01-10
          format: date
      required:
        - id
        - dn
        - taxCode
        - managerTaxCode
        - description
        - digitalHome
    Paginated:
      type: object
      additionalProperties: false
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Institution'
          maxItems: 100
          minItems: 10
        totalCount:
          type: integer
          format: int32
          maximum: 1000
          minimum: 10
      required:
        - items
        - totalCount
    ErrorResponse:
      properties:
        detail:
          description:
            A human readable explanation specific to this occurrence of the problem.
          example: Request took too long to complete.
          maxLength: 4096
          pattern: '^.{0,1024}$'
          type: string
        status:
          description:
            The HTTP status code generated by the origin server for this occurrence
            of the problem.
          example: 503
          exclusiveMaximum: true
          format: int32
          maximum: 600
          minimum: 100
          type: integer
        title:
          description:
            A short, summary of the problem type. Written in english and readable
          example: Service Unavailable
          maxLength: 64
          pattern: '^[ -~]{0,64}$'
          type: string
      additionalProperties: false
      required:
        - status
        - title