#!/bin/bash
SCRIPT_PATH="${BASH_SOURCE[0]}";
if ([ -h "${SCRIPT_PATH}" ]) then
  while([ -h "${SCRIPT_PATH}" ]) do SCRIPT_PATH=`readlink "${SCRIPT_PATH}"`; done
fi
pushd . > /dev/null
cd `dirname ${SCRIPT_PATH}` > /dev/null
SCRIPT_PATH=`pwd`;
popd  > /dev/null

repository=$DOCKER_REPO
replicas=$REPLICAS_NR

partyRegistryCategoriesURL=$PARTY_REGISTRY_CATEGORIES_URL
partyRegistryInstitutionsURL=$PARTY_REGISTRY_INSTITUTIONS_URL

name=$(cat $SCRIPT_PATH/../build.sbt | grep "name :=" | awk -F:= '{ print $2 }' | sed 's/\"//' | sed 's/\",//' | sed 's/ //' | tr '[:upper:]' '[:lower:]' | grep -v client)
# Temporary solution
imageName=interop-be-party-registry-proxy
#getting version from sbt
cd $SCRIPT_PATH/..
version=$(sbt -Dsbt.log.noformat=true 'inspect actual version' | grep "Setting: java.lang.String" | cut -d '=' -f2 | tr -d ' ')
cd $SCRIPT_PATH