package it.pagopa.pdnd.interop.uservice.partyregistryproxy.model

import spray.json.{DefaultJsonProtocol, JsArray, JsValue}
import spray.json._
//import java.nio.charset.StandardCharsets
//import java.nio.file.{Files, Paths}

object CategorySupport extends DefaultJsonProtocol {
  def load(): Categories = {
//    val path          = Paths.get("src/main/resources/categorie_ipa.json")
//    val content       = Files.readString(path, StandardCharsets.UTF_8)
    val json: JsValue = categories.parseJson
    val cats: Set[Category] = json.asJsObject.fields("records") match {
      case JsArray(elements) =>
        elements.flatMap {
          case JsArray(elements) =>
            Some(Category(elements(1).convertTo[String], elements(2).convertTo[String], elements(3).convertTo[String]))
          case _ => None
        }.toSet
      case _ => Set.empty[Category]
    }
    Categories(cats.toSeq)
  }

  val categories:String =
    """
      |{
      |  "records": [
      |    [
      |      1,
      |      "C17",
      |      "EntidiPrevidenzaedAssistenzaSocialeinContoEconomicoConsolidatoprivati",
      |      "EntiNazionalidiPrevidenzaedAssistenzaSocialeinContoEconomicoConsolidato",
      |      "P",
      |      "A",
      |      "P",
      |      "A",
      |      "P"
      |    ],
      |    [
      |      2,
      |      "C16",
      |      "EntidiPrevidenzaedAssistenzaSocialeinContoEconomicoConsolidatopubblici",
      |      "EntiNazionalidiPrevidenzaedAssistenzaSocialeinContoEconomicoConsolidato",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      3,
      |      "L37",
      |      "GestoridiPubbliciServizi",
      |      "GestoridiPubbliciServizi",
      |      "A",
      |      "A",
      |      "A",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      4,
      |      "SAG",
      |      "StazioniAppaltantiGestoridiPubbliciServizi",
      |      "GestoridiPubbliciServizi",
      |      "P",
      |      "A",
      |      "A",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      5,
      |      "L10",
      |      "AgenzieedEntiperilTurismo",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      6,
      |      "L19",
      |      "AgenzieedEntiRegionalidelLavoro",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      7,
      |      "L13",
      |      "AgenzieedEntiRegionalidiSviluppoAgricolo",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      8,
      |      "L2",
      |      "AgenzieedEntiRegionaliperlaFormazione,laRicercael'Ambiente",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      9,
      |      "C10",
      |      "AgenzieFiscali",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      10,
      |      "L20",
      |      "AgenzieRegionalieProvincialeperlaRappresentanzaNegoziale",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      11,
      |      "L21",
      |      "AgenzieRegionaliperleErogazioniinAgricoltura",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      12,
      |      "L22",
      |      "AgenzieRegionaliSanitarie",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      13,
      |      "L15",
      |      "Agenzie,EntieConsorziPubbliciperilDirittoalloStudioUniversitario",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      14,
      |      "L1",
      |      "AltriEntiLocali",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      15,
      |      "C13",
      |      "AutomobileClubFederatiACI",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      16,
      |      "C5",
      |      "Autorita'AmministrativeIndipendenti",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      17,
      |      "L40",
      |      "Autorita'diBacino",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      18,
      |      "L11",
      |      "Autorita'Portuali",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      19,
      |      "L39",
      |      "AziendeeConsorziPubbliciTerritorialiperl'EdiliziaResidenziale",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      20,
      |      "L46",
      |      "AziendeedAmministrazionidelloStatoadOrdinamentoAutonomo",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      21,
      |      "L8",
      |      "AziendeOspedaliere,AziendeOspedaliereUniversitarie,PoliclinicieIstitutidiRicoveroeCuraaCarattereScientificoPubblici",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      22,
      |      "L34",
      |      "AziendePubblichediServiziallaPersona",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      23,
      |      "L7",
      |      "AziendeSanitarieLocali",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      24,
      |      "L35",
      |      "CamerediCommercio,Industria,ArtigianatoeAgricolturaeloroUnioniRegionali",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      25,
      |      "L45",
      |      "Citta'Metropolitane",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      26,
      |      "L6",
      |      "ComunieloroConsorzieAssociazioni",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      27,
      |      "L12",
      |      "Comunita'MontaneeloroConsorzieAssociazioni",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      28,
      |      "L24",
      |      "ConsorzidiBacinoImbriferoMontano",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      29,
      |      "L28",
      |      "ConsorziInteruniversitaridiRicerca",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      30,
      |      "L42",
      |      "Consorziperl'AreadiSviluppoIndustriale",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      31,
      |      "L36",
      |      "ConsorzitraAmministrazioniLocali",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      32,
      |      "L44",
      |      "EntidiRegolazionedeiServiziIdricieodeiRifiuti",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      33,
      |      "C8",
      |      "EntieIstituzionidiRicercaPubblici",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      34,
      |      "C3",
      |      "EntiPubbliciNonEconomici",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      35,
      |      "C7",
      |      "EntiPubbliciProduttoridiServiziAssistenziali,RicreativieCulturali",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      36,
      |      "C14",
      |      "FederazioniNazionali,Ordini,CollegieConsigliProfessionali",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      37,
      |      "L16",
      |      "FondazioniLirico,Sinfoniche",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      38,
      |      "C11",
      |      "ForzediPoliziaadOrdinamentoCivileeMilitareperlaTuteladell'OrdineedellaSicurezzaPubblica",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      39,
      |      "L33",
      |      "IstitutidiIstruzioneStatalediOgniOrdineeGrado",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      40,
      |      "C12",
      |      "IstitutiZooprofilatticiSperimentali",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      41,
      |      "L43",
      |      "Istituzioniperl'AltaFormazioneArtistica,MusicaleeCoreutica-AFAM",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      42,
      |      "C2",
      |      "OrganiCostituzionaliediRilievoCostituzionale",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      43,
      |      "L38",
      |      "ParchiNazionali,ConsorzieEntiGestoridiParchieAreeNaturaliProtette",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      44,
      |      "C1",
      |      "PresidenzadelConsigliodeiMinistri,MinisterieAvvocaturadelloStato",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      45,
      |      "L5",
      |      "ProvinceeloroConsorzieAssociazioni",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      46,
      |      "L4",
      |      "Regioni,ProvinceAutonomeeloroConsorzieAssociazioni",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      47,
      |      "L31",
      |      "TeatriStabiliadIniziativaPubblica",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      48,
      |      "L18",
      |      "UnionidiComunieloroConsorzieAssociazioni",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      49,
      |      "L17",
      |      "Universita'eIstitutidiIstruzioneUniversitariaPubblici",
      |      "PubblicheAmministrazioni",
      |      "P",
      |      "P",
      |      "P",
      |      "P",
      |      "P"
      |    ],
      |    [
      |      50,
      |      "S01",
      |      "Societa'inContoEconomicoConsolidato",
      |      "Societa'inContoEconomicoConsolidato",
      |      "P",
      |      "A",
      |      "P",
      |      "A",
      |      "P"
      |    ],
      |    [
      |      51,
      |      "SA",
      |      "StazioniAppaltanti",
      |      "StazioniAppaltanti",
      |      "P",
      |      "A",
      |      "A",
      |      "A",
      |      "P"
      |    ]
      |  ]
      |}
      |""".stripMargin
}
