/**
 * Party Registry Proxy Server
 * This service is the proxy to the party registry
 *
 * The version of the OpenAPI document: {{version}}
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.pagopa.pdnd.interop.uservice.partyregistryproxy.client.model

import it.pagopa.pdnd.interop.uservice.partyregistryproxy.client.invoker.ApiModel

case class Category (
  code: String,
  name: String,
  kind: String
) extends ApiModel

