/**
 * Party Registry Proxy Server
 * This service is the proxy to the party registry
 *
 * The version of the OpenAPI document: {{version}}
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.pagopa.pdnd.interop.uservice.partyregistryproxy.client.model

import it.pagopa.pdnd.interop.uservice.partyregistryproxy.client.invoker.ApiModel

case class Institution (
  /* iPA code */
  id: String,
  /* o */
  o: Option[String] = None,
  /* ou */
  ou: Option[String] = None,
  /* aoo */
  aoo: Option[String] = None,
  /* institution fiscal code */
  fiscalCode: Option[String] = None,
  /* institution code */
  administrationCode: Option[String] = None,
  /* institution category */
  category: Option[String] = None,
  /* manager name */
  managerName: Option[String] = None,
  /* manager surname */
  managerSurname: Option[String] = None,
  /* institution description */
  description: String,
  /* digital institution address */
  digitalAddress: Option[String] = None
) extends ApiModel


